services:
  - type: web
    name: frontend-winter-2023-group-project # Change to your project name
    env: static
    buildCommand: cd ui; yarn install --production=false; yarn build
    staticPublishPath: ui/build/
    buildFilter:
      paths:
        - ui/**/*.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: backend-winter-2023-group-project # Change to your project name
    plan: free
    env: node
    buildCommand: cd api; yarn; npx knex migrate:latest
    startCommand: cd api; yarn run prod
    buildFilter:
      paths:
        - api/**/*.js
databases:
  - name: database-winter-2023-group-project # Change to your project name
    plan: free
    databaseName: trivia_db # Change to your database name
    ipAllowList: [] # only allow internal connections
